### PR TITLE
Add dark mode support

### PR DESCRIPTION
**Pull request by balthisar**
- Added a delegate to pre-process RTF files, allowing clients to re-color them for dark mode.
- Choose colors that will adapt automatically in dark mode.

### CODE REVIEW

**Comment by boyvanamstel** [comment]
Thanks for this @balthisar! Will test it asap. 👍

**Comment by boyvanamstel** [comment]
Your commit has been added to the `develop` branch: f670d70f8b9780dc9ec986c2d6bb3a1340683258

I hope you don't mind me reformatting some of the code to match the style of the original files. 👍

**Comment by balthisar** [comment]
> I hope you don't mind me reformatting some of the code to match the style of the original files.

Not at all!

**Comment by boyvanamstel** [comment]
And now it's been added to release 0.3.0 :).

Thanks again for your PR!

**Pull request closed without merging**
